/*
* generated by Xtext
*/
package com.avaloq.tools.dslsdk.checkcfg;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class CheckCfgUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return com.avaloq.tools.dslsdk.checkcfg.ui.internal.CheckCfgActivator.getInstance().getInjector("com.avaloq.tools.dslsdk.checkcfg.CheckCfg");
	}
	
}
