/*
* generated by Xtext
*/
package com.avaloq.tools.dslsdk.check;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class CheckUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return com.avaloq.tools.dslsdk.check.ui.internal.CheckActivator.getInstance().getInjector("com.avaloq.tools.dslsdk.check.Check");
	}
	
}
