/*
* generated by Xtext
*/
package com.avaloq.tools.dslsdk.checkcfg.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class CheckCfgAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("com/avaloq/tools/dslsdk/checkcfg/parser/antlr/internal/InternalCheckCfg.tokens");
	}
}
