/*
 * generated by Xtext
 */
package com.avaloq.tools.dslsdk.check.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class CheckExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return com.avaloq.tools.dslsdk.check.ui.internal.CheckActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return com.avaloq.tools.dslsdk.check.ui.internal.CheckActivator.getInstance().getInjector("com.avaloq.tools.dslsdk.check.Check");
	}
	
}
